inherit_from: .rubocop_todo.yml

AllCops:
    TargetRubyVersion: 2.4

Style/Documentation:
    Enabled: False
Style/HashSyntax:
    EnforcedStyle: hash_rockets
Style/TrailingCommaInHashLiteral:
    EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
    EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
    EnforcedStyleForMultiline: comma

Layout/HashAlignment:
    EnforcedHashRocketStyle: table
Layout/FirstHashElementIndentation:
    EnforcedStyle: consistent
Metrics/ParameterLists:
    Enabled: False

Style/StderrPuts:
  Enabled: false
Style/WordArray:
  Enabled: false
