inherit_from: .rubocop_todo.yml

AllCops:
    TargetRubyVersion: 2.4

Style/Documentation:
    Enabled: False
Style/HashSyntax:
    EnforcedStyle: hash_rockets
Style/TrailingCommaInHashLiteral:
    EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
    EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
    EnforcedStyleForMultiline: comma

Layout/AlignHash:
    EnforcedHashRocketStyle: table
Layout/IndentHash:
    EnforcedStyle: consistent
